# 源镜像
FROM php-base

# 维护信息
MAINTAINER Rytia <admin@zzfly.net>
WORKDIR /var/www/html
EXPOSE 8000

# 拉去最新源码
ADD https://github.com/scau-emotion/manage-api-service/archive/master.zip /var/www/html
RUN unzip master.zip
RUN cp -ar ./manage-api-service-master/. ./
RUN rm -r ./manage-api-service-master
RUN cp .env.test .env

# 下载依赖
RUN composer install --no-ansi --no-interaction

# 数据库迁移
RUN php artisan migrate --no-ansi --no-interaction

# 单元测试
RUN /var/www/html/vendor/bin/phpunit

# 运行
ENTRYPOINT ["/usr/local/bin/php","-S","0.0.0.0:8000", "-t", "public"]
